// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {netmon} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetSpeeds():Promise<Record<string, netmon.InterfaceSpeed>>;

export function GetState():Promise<main.AppState>;

export function ListInterfaces():Promise<Array<string>>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;
