// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {netmon} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetSpeeds():Promise<Record<string, netmon.InterfaceSpeed>>;

export function GetWindowMode():Promise<string>;

export function ListInterfaces():Promise<Array<string>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveWidgetPosition(arg1:number,arg2:number):Promise<void>;

export function SetMainWindowFocus(arg1:boolean):Promise<void>;

export function SetWidgetPositionX11(arg1:number,arg2:number):Promise<void>;

export function ToggleWidget(arg1:boolean):Promise<void>;

export function UpdateWindowPosition(arg1:number,arg2:number):Promise<void>;

export function UpdateWindowSize(arg1:number,arg2:number):Promise<void>;
