// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSpeeds() {
  return window['go']['main']['App']['GetSpeeds']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
